### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [the10thWiz/zsh-prompt-generator#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by unixorn** [comment]
Please also rename the repo to something less generic than zsh-theme - even naming it after your github username will make it easier for people to find.

**Comment by the10thWiz** [comment]
Sorry for the late reply. I have been with school work and did not notice your comments. I didn't really expect anyone else to find this, so I didn't put much effort into naming or documenting it.

I have added a readme and a license, along with a screenshot. I also updated the name to `zsh-theme-generator`, I hope that's unique enough.

Thanks!
